# Generated by Django 4.1.3 on 2022-11-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactur_brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Top_flavour', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='Relation', null=True, on_delete=django.db.models.deletion.CASCADE, to='star_nv.musician'),
        ),
        migrations.AlterField(
            model_name='student',
            name='shrit_size',
            field=models.CharField(blank=True, choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L')], default='S', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_pizza', models.ManyToManyField(to='star_nv.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='star_nv.manufactur', verbose_name='car_R')),
            ],
        ),
    ]
