# Generated by Django 4.1.3 on 2022-11-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0005_ox_person_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='student_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_group', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
