# Generated by Django 4.1.3 on 2022-11-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0006_blog_student_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_2',
            name='age',
            field=models.PositiveIntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_2',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
