# Generated by Django 4.1.3 on 2022-11-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0007_student_2_age_student_2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'album',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
