# Generated by Django 4.1.3 on 2022-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0008_album_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('home_group', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['first_name'],
                'abstract': False,
            },
        ),
    ]
