# Generated by Django 4.1.3 on 2022-11-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0012_author_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
