# Generated by Django 4.1.3 on 2022-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_nv', '0016_publication_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ManyToManyField(blank=True, to='star_nv.author'),
        ),
    ]
