from django.contrib import admin
from star_nv.models import *


admin.site.register(Person_1)
admin.site.register(Group)
admin.site.register(Membership)
admin.site.register(Manufactur)
admin.site.register(Car)
admin.site.register(student)
admin.site.register(Topping)
admin.site.register(Pizza)
admin.site.register(person)
admin.site.register(musician)
admin.site.register(album)
admin.site.register(Ox)
admin.site.register(person_2)
admin.site.register(album_1)
admin.site.register(student_2)
admin.site.register(Student_3)
admin.site.register(Blog)
admin.site.register(Author)
admin.site.register(Entry)
admin.site.register(Publisher)
admin.site.register(Author1)
admin.site.register(Book1)
admin.site.register(Item)
admin.site.register(Cart)
admin.site.register(Publisher3)
admin.site.register(Book3)
admin.site.register(Store)

